export const FORM_SELECTORS = {
    addFullName: "add-full-name-element",
    firstNameField: "first-name-text-field",
    lastNameField: "last-name-text-field",
    addPhoneNumber: "add-phone-number-element",
    phoneNumberField: "phone-number-input-field",
    addSingleChoice: "add-single-choice-element",
    addMultiChoice: "add-multi-choice-element",
    submitButton: "start-or-submit-button",
    publishButton: "publish-button",
    toastrSuccess: "toastr-success-container",
    publishPreview: "publish-preview-button",
    emailField: "email-text-field",
    addFormButton: "add-form-button",
    startFromScratchButton: "start-from-scratch-button",
    elementPropertiesDropdown: "element-properties-dropdown",
    spinner: "neeto-ui-spinner",
    singleChoiceContainer: "single-choice-options-container",
    multiChoiceContainer: "multi-choice-options-container",
    propertiesPanel: "properties-panel",
    contentTextField: "content-text-field",
    addBulkOption: "add-bulk-option-link",
    bulkOptionsTextarea: "bulk-add-options-textarea",
    bulkOptionsDoneButton: "bulk-add-options-done-button",
    randomizeSwitch: "randomize-switch-label",
    addOptionLink: "add-option-link",
    hideQuestionToggle: "hide-question-toggle-label",
    
};
